services:
  - type: web
    name: gym-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: NODE_ENV
        value: production

databases:
  - name: gym-postgres
    plan: free
    databaseName: gym_db
    user: gym_user
