services:
  - type: web
    name: gym-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: NODE_ENV
        value: production
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: gym-postgres
    plan: free
    databaseName: gym_db
    user: gym_user